# Autogenerated file
onerror {
	quit -f -code 1
}
vmap -c
if [file exists sim_build/work] {vdel -lib sim_build/work -all}
vlib sim_build/work
vmap work sim_build/work
vlog -work work +define+COCOTB_SIM -sv -timescale 1ns/1ps -mfcu +acc  /mnt/d/D/TEC/2024/S2/Proyecto_de_diseno/Pruebas/ALU/A1_N.sv /mnt/d/D/TEC/2024/S2/Proyecto_de_diseno/Pruebas/ALU/Absolute_N.sv /mnt/d/D/TEC/2024/S2/Proyecto_de_diseno/Pruebas/ALU/Adder_Subtractor_N.sv /mnt/d/D/TEC/2024/S2/Proyecto_de_diseno/Pruebas/ALU/Adder_with_carries_N.sv /mnt/d/D/TEC/2024/S2/Proyecto_de_diseno/Pruebas/ALU/Adder_with_carry_in_N.sv /mnt/d/D/TEC/2024/S2/Proyecto_de_diseno/Pruebas/ALU/ALU_RV32I.sv /mnt/d/D/TEC/2024/S2/Proyecto_de_diseno/Pruebas/ALU/Multiplexer_MxN.sv /mnt/d/D/TEC/2024/S2/Proyecto_de_diseno/Pruebas/ALU/SLT_U_N.sv
vsim  -onfinish exit -pli /usr/local/lib/python3.10/dist-packages/cocotb/libs/libcocotbvpi_modelsim.so   sim_build/work.ALU_RV32I
onbreak resume
run -all
quit
